sudo: required
dist: trusty
language: c

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-5 g++-5 -y

addons:
  apt:
    packages:
      - libboost-all-dev
      - libmicrohttpd-dev
      - libprotobuf-dev
      - libusb-1.0-0-dev

script:
  - ./build.sh
